### ISSUE TITLE
CUDA error when run pretrain

### ISSUE THREAD

**Issue by chanyn** [facebookresearch/DepthContrast#21]
Hi, I want to pretrain on my own dataset.
But I met CUDA error (spconv):

`RuntimeError: CUDA error: an illegal memory access was encountered`.

`Traceback (most recent call last):
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/xuhang/jch/works/DepthContrast/main.py", line 129, in main_worker
    run_phase('train', train_loader, model, optimizer, train_criterion, epoch, args, cfg, logger, tb_writter)
  File "/home/xuhang/jch/works/DepthContrast/main.py", line 158, in run_phase
    embedding = model(sample)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/jch/works/DepthContrast/models/base_ssl3d_model.py", line 268, in forward
    return self.multi_input_with_head_mapping_forward(batch)
  File "/home/xuhang/jch/works/DepthContrast/models/base_ssl3d_model.py", line 71, in multi_input_with_head_mapping_forward
    outputs = self._single_input_forward(batch[input_key], feature_names, input_key, input_idx)
  File "/home/xuhang/jch/works/DepthContrast/models/base_ssl3d_model.py", line 108, in _single_input_forward
    feats = self.trunk[target](batch, feature_names)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/jch/works/DepthContrast/models/trunks/spconv_unet.py", line 225, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
RuntimeError: CUDA error: an illegal memory access was encountered (copy_kernel_cuda at /pytorch/aten/src/ATen/native/cuda/Copy.cu:180)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fe17840a193 in /home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6
/site-packages/torch/lib/libc10.so)
`

I can not find the reason, only the input is different between this project (the point cloud is loaded from .bin files not .npy).

Has anyone encountered a similar problem?

My runing commend:

`CUDA_VISIBLE_DEVICES=1,2,3,4 python main.py configs/point_vox_lidar.yaml --multiprocessing-distributed --world-size 1 --rank 0 --ngpus 4`

My environment is:
Pytorch1.4 + cuda10.1 + spconv1.2

**Comment by chanyn** [comment]
If I run 1 GPU,  `python main.py configs/point_vox_lidar.yaml --multiprocessing-distributed --world-size 1 --rank 0 --ngpus 1`

the error is:

`==============================   Train data   ==============================
<datasets.depth_dataset.DepthContrastDataset object at 0x7f104424aef0>
{'loss_type': 'cross_entropy', 'name': 'NCELossMoco'}
============================== Epoch 0 ==============================
LR: [0.12]

train: Epoch 0
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main()
  File "main.py", line 74, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args, cfg))
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGFPE
(depthcontrast) xuhang@noah008:~/jch/works/DepthContrast$ /home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 38 leaked semaphores to clean up at shutdown
  len(cache))
`

**Comment by zaiweizhang** [comment]
Hi chanyn, I met that issue before and it was because of CUDA running out of memory. A smaller batch size works for me. I am not sure if you have tried that.

**Comment by chanyn** [comment]
> Hi chanyn, I met that issue before and it was because of CUDA running out of memory. A smaller batch size works for me. I am not sure if you have tried that.

Hi zaiwei,  if I try small batch size `BATCHSIZE_PER_REPLICA: 3`
But I met:
`Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main()
  File "main.py", line 74, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args, cfg))
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 2 terminated with signal SIGFPE
`

And a strange thing is that the device 2 occupies large memory (~11620M) others only ~3000+M.

**Comment by chanyn** [comment]
> Hi chanyn, I met that issue before and it was because of CUDA running out of memory. A smaller batch size works for me. I am not sure if you have tried that.

Hi zaiwei, I set `multiprocessing-distributeduse=False` and find `Floating point exception (core dumped)`.

`==============================   Train data   ==============================
<datasets.depth_dataset.DepthContrastDataset object at 0x7f99fb542f60>
{'loss_type': 'cross_entropy', 'name': 'NCELossMoco'}
============================== Epoch 0 ==============================
LR: [0.12]`

`train: Epoch 0
Floating point exception (core dumped)`

I have no idea for this issue.

**Comment by zaiweizhang** [comment]
Does it work for one-gpu setting?

**Comment by chanyn** [comment]
> Does it work for one-gpu setting?

No, one-gpu will raise `Floating point exception (core dumped)`.

I try to update my pytorch version to 1.5.1.

**Comment by zaiweizhang** [comment]
For one-gpu setting, you used this line:
python main.py /path/to/cfg/file

**Comment by chanyn** [comment]
I update pytorch==1.5.1 and run the command: `CUDA_VISIBLE_DEVICES=2 python main.py `

Then I have meet an error `unknown device type`.


==============================   Args   ==============================
cfg                            configs/point_vox_lidar_jch.yaml
quiet                          False
world_size                     -1
rank                           0
dist_url                       tcp://localhost:15475
dist_backend                   nccl
seed                           None
gpu                            0
ngpus                          8
multiprocessing_distributed    False



train: Epoch 0
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main()
  File "main.py", line 77, in main
    main_worker(args.gpu, ngpus_per_node, args, cfg)
  File "main.py", line 129, in main_worker
    run_phase('train', train_loader, model, optimizer, train_criterion, epoch, args, cfg, logger, tb_writter)
  File "main.py", line 158, in run_phase
    embedding = model(sample)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/jch/works/DepthContrast/models/base_ssl3d_model.py", line 268, in forward
    return self.multi_input_with_head_mapping_forward(batch)
  File "/home/xuhang/jch/works/DepthContrast/models/base_ssl3d_model.py", line 71, in multi_input_with_head_mapping_forward
    outputs = self._single_input_forward(batch[input_key], feature_names, input_key, input_idx)
  File "/home/xuhang/jch/works/DepthContrast/models/base_ssl3d_model.py", line 108, in _single_input_forward
    feats = self.trunk[target](batch, feature_names)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/jch/works/DepthContrast/models/trunks/spconv_unet.py", line 225, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
ValueError: /home/xuhang/jch/packages/spconv1.2/spconv/src/spconv/spconv_ops.cc 87
unknown device type

**Comment by chanyn** [comment]
I set `BATCHSIZE_PER_REPLICA: 4`, the one GPU setting is running!

But multi-gpus setting is sucked at:

==============================   Train data   ==============================
<datasets.depth_dataset.DepthContrastDataset object at 0x7f48417997b8>
{'loss_type': 'cross_entropy', 'name': 'NCELossMoco'}

**Comment by chanyn** [comment]
Furthermore, I set LR=0.02 due to BATCHSIZE_PER_REPLICA=4. Is this right?

**Comment by zaiweizhang** [comment]
The loss looks fine to me. In the first couple of epochs, the loss will increase as it gradually builds the negative examples queue. This LR 0.12 was for batch size 1024, and it usually correlates well with the batch size. So for your case, I may even suggest a smaller learning rate.
